### ISSUE TITLE
Game loading stuck

### ISSUE THREAD

**Issue by 5cover** [aBARICHELLO/Firewatch-noclip#2]
Hi, I've followed your instructions, but I can't play the game is stuck on the loading screen.
Thx for help

**Comment by abarichello** [comment]
Hello, I believe the generated DLL is different for each system/build used. It would be better for you to generate your own since i can't guarantee that mine will work with your system.
I used [dnspy](https://github.com/0xd4d/dnSpy) to decompile and recompile the assembly-csharp dll. You need to open the DLL with dnspy and include the extra code that is in this repository, the comments should help you.
If you need any help feel free to comment here.

**Comment by jrbrobodroid** [comment]
well how do you add that code i have everything how do i add it

**Comment by Luminous478** [comment]
I have the same problem how do you add it?
